# Generated by Django 4.0.4 on 2022-05-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_basejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior'), ('TeamLead', 'TeamLead')], default='Junior', max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_second', to='main.basejob')),
            ],
        ),
    ]
