# Generated by Django 4.0.4 on 2022-05-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_baseemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseemployee',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
