# Generated by Django 4.0.1 on 2022-05-31 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_baseemployee_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseemployee',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='kasb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_first', to='main.jobs'),
        ),
    ]
