# Generated by Django 4.0.1 on 2022-05-31 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_full_name_baseemployee_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=11)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_first', to='main.jobs')),
            ],
        ),
        migrations.AlterField(
            model_name='baseemployee',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_second', to='main.basejob'),
        ),
        migrations.DeleteModel(
            name='Xodimlar',
        ),
    ]
