# Generated by Django 4.0.1 on 2022-06-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_employee1_alter_baseemployee_job_delete_xodimlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=8, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='employee1',
            old_name='first_name',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='employee1',
            old_name='last_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='employee1',
            name='birthday',
        ),
    ]
