# Generated by Django 4.0.1 on 2022-06-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_register_rename_first_name_employee1_degree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee1',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
