# Generated by Django 4.0.1 on 2022-06-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_phone_number_employee1_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee1',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_first', to='main.jobs'),
            preserve_default=False,
        ),
    ]
