# Generated by Django 4.0.1 on 2022-06-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_employee1_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee1',
            name='degree',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior'), ('TeamLead', 'TeamLead')], default='Junior', max_length=100),
        ),
    ]
