# Generated by Django 4.0.1 on 2022-06-04 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_employee1_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee1',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_first', to='main.jobs'),
        ),
    ]
