# Generated by Django 4.0.1 on 2022-06-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_employee1_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee1',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
