# Generated by Django 4.0.1 on 2022-06-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_employee1_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='staff',
            field=models.CharField(choices=[('Recieption', 'Recieption'), ('Admin', 'Admin')], default='Admin', max_length=10),
        ),
    ]
