# Generated by Django 4.0.1 on 2022-06-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_register_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='staff',
        ),
    ]
